AllCops:
  Include:
    - '**/Gemfile'
  Exclude:
    - '**/Rakefile'
    - 'bin/**'
Documentation:
    Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/ModuleLength:
  Exclude:
    - "**/*_spec.rb"
Metrics/BlockLength:
  Exclude:
    - "**/*_spec.rb"
